const field = (name, type, options = {}) => ({ name, type, ...options });

const id = () =>
  field("id", "uuid", {
    primary: true,
    required: true,
    default: "uuid",
    readonly: true,
    hidden: true,
  });

const publicationStatus = () =>
  field("status", "string", {
    required: true,
    default: "draft",
    choices: ["draft", "published", "archived"],
    index: true,
  });

const timestamps = () => [
  field("created_at", "timestamp", {
    special: ["date-created"],
    readonly: true,
    hidden: true,
  }),
  field("updated_at", "timestamp", {
    special: ["date-updated"],
    readonly: true,
    hidden: true,
  }),
];

const contentFields = (...fields) => [
  id(),
  publicationStatus(),
  ...fields,
  ...timestamps(),
];

const translations = () =>
  field("translations", "json", {
    note: "Future translations keyed by locale, for example ru-RU.",
  });

export const schemaBlueprint = {
  version: 3,
  collections: [
    { name: "group_site", folder: true, icon: "web", sort: 1, fields: [] },
    { name: "group_catalog", folder: true, icon: "inventory_2", sort: 2, fields: [] },
    { name: "group_content", folder: true, icon: "article", sort: 3, fields: [] },
    { name: "group_sales", folder: true, icon: "request_quote", sort: 4, fields: [] },
    { name: "group_settings", folder: true, icon: "settings", sort: 5, fields: [] },
    {
      name: "site_settings",
      icon: "settings",
      singleton: true,
      fields: [
        id(),
        field("company_name", "string", { required: true }),
        field("phone", "string", { required: true }),
        field("email", "string", { required: true }),
        field("messengers", "json"),
        field("social_links", "json"),
        field("address", "text"),
        field("city", "string"),
        field("working_hours", "string"),
        field("delivery_region", "string"),
        field("logo", "uuid", {
          relatedCollection: "directus_files",
          interface: "file-image",
        }),
        field("favicon", "uuid", {
          relatedCollection: "directus_files",
          interface: "file-image",
        }),
        field("default_og_image", "uuid", {
          relatedCollection: "directus_files",
        }),
        field("seo_title", "string"),
        field("seo_description", "text"),
        field("og_title", "string"),
        field("og_description", "text"),
        field("primary_color", "string", { default: "#245c2a" }),
        field("accent_color", "string", { default: "#f2c94c" }),
        field("primary_cta_text", "string"),
        field("primary_cta_url", "string"),
        field("footer_text", "text"),
        field("footer_disclaimer", "text"),
        field("inn", "string"),
        field("kpp", "string"),
        field("ogrn", "string"),
        field("legal_address", "text"),
        field("legal_name", "string"),
        field("vat_info", "string"),
        field("requisites_url", "string"),
        field("documents_url", "string"),
        field("company_image", "uuid", { relatedCollection: "directus_files" }),
        field("yandex_metrica_id", "string"),
        field("gtm_id", "string"),
        translations(),
        ...timestamps(),
      ],
    },
    {
      name: "home_page",
      icon: "home",
      singleton: true,
      fields: contentFields(
        field("source_page", "uuid", {
          required: true,
          relatedCollection: "pages",
          index: true,
        }),
        field("h1", "string", { required: true }),
        field("hero_title", "string", { required: true }),
        field("hero_text", "text", { required: true }),
        field("hero_image", "uuid", {
          required: true,
          relatedCollection: "directus_files",
          interface: "file-image",
        }),
        field("hero_image_alt", "string", { required: true }),
        field("hero_primary_button_text", "string"),
        field("hero_primary_button_url", "string"),
        field("hero_secondary_button_text", "string"),
        field("hero_secondary_button_url", "string"),
        field("hero_search_label", "string", { required: true }),
        field("hero_search_placeholder", "string", { required: true }),
        field("hero_search_button_text", "string", { required: true }),
        field("hero_bulk_prompt", "string", { required: true }),
        field("hero_bulk_link_text", "string", { required: true }),
        field("hero_bulk_link_url", "string", { required: true }),
        field("hero_excel_link_text", "string", { required: true }),
        field("hero_excel_link_url", "string", { required: true }),
        field("hero_photo_link_text", "string", { required: true }),
        field("hero_photo_link_url", "string", { required: true }),
        field("seo_title", "string"),
        field("seo_description", "text"),
        field("canonical_url", "text"),
        field("og_title", "string"),
        field("og_description", "text"),
        field("og_image", "uuid", { relatedCollection: "directus_files" }),
        field("is_indexable", "boolean", { default: true }),
        field("sections", "alias", {
          interface: "list-o2m",
          special: ["o2m"],
        }),
        translations(),
      ),
    },
    {
      name: "pages",
      icon: "web",
      fields: contentFields(
        field("title", "string", { required: true }),
        field("slug", "string", { required: true, unique: true, index: true }),
        field("page_type", "string", {
          required: true,
          choices: [
            "home",
            "catalog",
            "about",
            "delivery",
            "contacts",
            "privacy_policy",
            "thank_you",
            "articles",
            "standard",
          ],
          index: true,
        }),
        field("h1", "string", { required: true }),
        field("eyebrow", "string"),
        field("intro", "text"),
        field("seo_title", "string"),
        field("seo_description", "text"),
        field("seo_text", "text"),
        field("og_image", "uuid", { relatedCollection: "directus_files" }),
        field("canonical_url", "text"),
        field("is_indexable", "boolean", { default: true }),
        translations(),
      ),
    },
    {
      name: "page_sections",
      icon: "view_quilt",
      fields: contentFields(
        field("home_page", "uuid", {
          relatedCollection: "home_page",
          oneField: "sections",
          index: true,
        }),
        field("page", "uuid", {
          relatedCollection: "pages",
          index: true,
          onDelete: "CASCADE",
        }),
        field("section_type", "string", {
          required: true,
          choices: [
            "hero",
            "categories",
            "company_trust",
            "featured_products",
            "advantages",
            "steps",
            "cta",
            "catalog_preview",
            "seo_text",
            "lead_form",
            "parts_request",
            "recent_supplies",
            "faq",
            "contacts",
            "articles",
            "custom",
          ],
          index: true,
        }),
        field("title", "string"),
        field("subtitle", "string"),
        field("text", "text"),
        field("image", "uuid", {
          relatedCollection: "directus_files",
          interface: "file-image",
        }),
        field("image_alt", "string"),
        field("button_text", "string"),
        field("button_url", "string"),
        field("items", "json"),
        field("settings", "json"),
        field("is_visible", "boolean", { default: true }),
        field("sort_order", "integer", { default: 0, index: true }),
        translations(),
      ),
    },
    {
      name: "navigation_items",
      icon: "menu",
      fields: contentFields(
        field("label", "string", { required: true }),
        field("url", "string", { required: true }),
        field("parent", "uuid", {
          relatedCollection: "navigation_items",
        }),
        field("location", "string", {
          required: true,
          default: "header",
          choices: ["header", "footer", "legal"],
          index: true,
        }),
        field("open_in_new_tab", "boolean", { default: false }),
        field("is_visible", "boolean", { default: true }),
        field("sort_order", "integer", { default: 0, index: true }),
        translations(),
      ),
    },
    {
      name: "categories",
      icon: "category",
      fields: contentFields(
        field("title", "string", { required: true }),
        field("slug", "string", { required: true, unique: true, index: true }),
        field("parent", "uuid", { relatedCollection: "categories" }),
        field("description", "text"),
        field("image", "uuid", { relatedCollection: "directus_files" }),
        field("image_alt", "string"),
        field("icon", "uuid", { relatedCollection: "directus_files" }),
        field("icon_alt", "string"),
        field("h1", "string"),
        field("seo_title", "string"),
        field("seo_description", "text"),
        field("seo_text", "text"),
        field("intro", "text"),
        field("selection_guide", "json"),
        field("internal_links", "json"),
        field("og_image", "uuid", { relatedCollection: "directus_files" }),
        field("faq", "json"),
        field("is_indexable", "boolean", { default: true, index: true }),
        field("redirect_target", "string"),
        field("sort_order", "integer", { default: 0, index: true }),
        field("show_on_homepage", "boolean", { default: false }),
        translations(),
      ),
    },
    {
      name: "articles",
      icon: "article",
      fields: contentFields(
        field("title", "string", { required: true }),
        field("slug", "string", { required: true, unique: true, index: true }),
        field("excerpt", "text", { required: true }),
        field("content", "text", {
          required: true,
          interface: "input-rich-text-html",
        }),
        field("cover_image", "uuid", {
          relatedCollection: "directus_files",
        }),
        field("image_alt", "string"),
        field("published_at", "timestamp", { required: true, index: true }),
        field("category_label", "string"),
        field("reading_time_minutes", "integer"),
        field("author", "string"),
        field("reviewer", "string"),
        field("sources", "json"),
        field("related_categories", "json"),
        field("related_products", "json"),
        field("is_featured", "boolean", { default: false, index: true }),
        field("sort_order", "integer", { default: 0, index: true }),
        field("seo_title", "string"),
        field("seo_description", "text"),
        field("og_image", "uuid", { relatedCollection: "directus_files" }),
        translations(),
      ),
    },
    {
      name: "products",
      icon: "inventory_2",
      fields: contentFields(
        field("title", "string", { required: true }),
        field("slug", "string", { required: true, unique: true, index: true }),
        field("sku", "string", { required: true, unique: true, index: true }),
        field("category", "uuid", {
          relatedCollection: "categories",
          index: true,
        }),
        field("short_description", "text"),
        field("full_description", "text"),
        field("seo_text", "text"),
        field("main_image", "uuid", { relatedCollection: "directus_files" }),
        field("gallery", "json"),
        field("price", "decimal", { precision: 12, scale: 2 }),
        field("currency", "string", { required: true, default: "RUB" }),
        field("price_status", "string", {
          required: true,
          default: "fixed",
          choices: ["fixed", "on_request", "hidden"],
          index: true,
        }),
        field("availability_status", "string", {
          required: true,
          default: "on_request",
          choices: ["in_stock", "on_request", "out_of_stock"],
          index: true,
        }),
        field("brand", "string"),
        field("mpn", "string", { index: true }),
        field("gtin", "string", { index: true }),
        field("part_type", "string", {
          choices: ["original", "oem", "analog"],
        }),
        field("delivery_status", "string"),
        field("specifications", "json"),
        field("documents", "json"),
        field("source_name", "string"),
        field("source_url", "string"),
        field("verified_at", "timestamp"),
        field("reviewed_by", "string"),
        field("seo_title", "string"),
        field("seo_description", "text"),
        field("og_image", "uuid", { relatedCollection: "directus_files" }),
        field("image_alt", "string"),
        field("seo_quality_status", "string", {
          default: "pending",
          choices: ["pending", "reviewed", "published", "needs_fix"],
          index: true,
        }),
        field("is_indexable", "boolean", { default: true, index: true }),
        field("sort_order", "integer", { default: 0, index: true }),
        field("popularity_score", "integer", { default: 0, index: true }),
        field("is_featured", "boolean", { default: false, index: true }),
        field("show_on_homepage", "boolean", {
          default: false,
          index: true,
        }),
        field("cta_text", "string"),
        field("related_products", "json"),
        field("lead_form", "uuid", { relatedCollection: "lead_forms" }),
        translations(),
      ),
    },
    {
      name: "faq_items",
      icon: "quiz",
      fields: contentFields(
        field("question", "string", { required: true }),
        field("answer", "text", { required: true }),
        field("page", "uuid", { relatedCollection: "pages" }),
        field("category", "uuid", { relatedCollection: "categories" }),
        field("product", "uuid", { relatedCollection: "products" }),
        field("sort_order", "integer", { default: 0 }),
        field("is_visible", "boolean", { default: true }),
        translations(),
      ),
    },
    {
      name: "lead_forms",
      icon: "dynamic_form",
      fields: contentFields(
        field("code", "string", { required: true, unique: true, index: true }),
        field("title", "string", { required: true }),
        field("description", "text"),
        field("button_text", "string"),
        field("success_message", "text"),
        field("success_url", "string", { default: "/thank-you" }),
        field("fields", "json"),
        field("turnstile_required", "boolean", { default: true }),
        field("is_active", "boolean", { default: true }),
        translations(),
      ),
    },
    {
      name: "leads",
      icon: "inbox",
      fields: [
        id(),
        field("status", "string", {
          required: true,
          default: "new",
          choices: ["new", "in_progress", "closed", "spam"],
          index: true,
        }),
        field("name", "string"),
        field("phone", "string", { required: true }),
        field("email", "string"),
        field("message", "text"),
        field("product", "uuid", { relatedCollection: "products" }),
        field("category", "uuid", { relatedCollection: "categories" }),
        field("lead_form", "uuid", { relatedCollection: "lead_forms" }),
        field("page_url", "text", { required: true }),
        field("utm_source", "string"),
        field("utm_medium", "string"),
        field("utm_campaign", "string"),
        field("utm_content", "string"),
        field("utm_term", "string"),
        field("request_items", "json", {
          note: "Normalized parts request lines: article and quantity.",
        }),
        field("attachments", "json", {
          note: "Directus file IDs uploaded with a parts request.",
        }),
        field("manager_comment", "text"),
        ...timestamps(),
      ],
    },
    {
      name: "contact_channels",
      icon: "contact_phone",
      fields: contentFields(
        field("page_section", "uuid", {
          relatedCollection: "page_sections",
          index: true,
        }),
        field("channel_type", "string", {
          required: true,
          choices: ["phone", "email", "messenger", "address", "hours"],
          index: true,
        }),
        field("label", "string", { required: true }),
        field("value", "string", { required: true }),
        field("url", "string"),
        field("icon", "string"),
        field("sort_order", "integer", { default: 0, index: true }),
        field("is_visible", "boolean", { default: true }),
        translations(),
      ),
    },
    {
      name: "recent_supplies",
      icon: "local_shipping",
      fields: contentFields(
        field("image", "uuid", { relatedCollection: "directus_files" }),
        field("image_alt", "string"),
        field("equipment_type", "string"),
        field("positions", "json"),
        field("region", "string"),
        field("delivery_term", "string"),
        field("supply_format", "string"),
        field("supplied_at", "timestamp", { index: true }),
        field("sort_order", "integer", { default: 0, index: true }),
        translations(),
      ),
    },
    {
      name: "product_images",
      icon: "photo_library",
      fields: contentFields(
        field("product", "uuid", {
          required: true,
          relatedCollection: "products",
          index: true,
          onDelete: "CASCADE",
        }),
        field("image", "uuid", {
          required: true,
          relatedCollection: "directus_files",
        }),
        field("alt_text", "string"),
        field("sort_order", "integer", { default: 0, index: true }),
        translations(),
      ),
    },
    {
      name: "product_specifications",
      icon: "table_chart",
      fields: contentFields(
        field("product", "uuid", {
          required: true,
          relatedCollection: "products",
          index: true,
          onDelete: "CASCADE",
        }),
        field("group_name", "string"),
        field("name", "string", { required: true }),
        field("value", "string", { required: true }),
        field("unit", "string"),
        field("sort_order", "integer", { default: 0, index: true }),
        translations(),
      ),
    },
    {
      name: "product_documents",
      icon: "description",
      fields: contentFields(
        field("product", "uuid", {
          required: true,
          relatedCollection: "products",
          index: true,
          onDelete: "CASCADE",
        }),
        field("file", "uuid", {
          required: true,
          relatedCollection: "directus_files",
        }),
        field("title", "string"),
        field("sort_order", "integer", { default: 0, index: true }),
        translations(),
      ),
    },
    {
      name: "seo_redirects",
      icon: "alt_route",
      fields: [
        id(),
        field("old_url", "string", { required: true, unique: true, index: true }),
        field("new_url", "string", { required: true }),
        field("status_code", "integer", {
          required: true,
          default: 301,
          choices: [301, 302],
        }),
        field("is_active", "boolean", { default: true, index: true }),
        ...timestamps(),
      ],
    },
    {
      name: "orders",
      icon: "shopping_cart_checkout",
      fields: [
        id(),
        field("status", "string", {
          required: true,
          default: "new",
          choices: [
            "new",
            "in_progress",
            "confirmed",
            "shipped",
            "delivered",
            "cancelled",
          ],
          index: true,
        }),
        field("customer_name", "string", { required: true }),
        field("phone", "string", { required: true }),
        field("email", "string"),
        field("comment", "text"),
        field("total", "decimal", { precision: 12, scale: 2 }),
        field("currency", "string", { required: true, default: "RUB" }),
        field("page_url", "text", { required: true }),
        field("utm_source", "string"),
        field("utm_medium", "string"),
        field("utm_campaign", "string"),
        field("utm_content", "string"),
        field("utm_term", "string"),
        field("manager_comment", "text"),
        ...timestamps(),
      ],
    },
    {
      name: "order_items",
      icon: "inventory",
      note: "Snapshot line items for an order. order→products is SET NULL on product deletion to preserve history.",
      fields: [
        id(),
        field("order", "uuid", {
          required: true,
          relatedCollection: "orders",
          index: true,
          onDelete: "CASCADE",
        }),
        field("product", "uuid", {
          relatedCollection: "products",
          index: true,
        }),
        field("sku_snapshot", "string"),
        field("title_snapshot", "text"),
        field("unit_price", "decimal", { precision: 12, scale: 2 }),
        field("quantity", "integer", { required: true, default: 1 }),
        field("currency", "string", { required: true, default: "RUB" }),
        ...timestamps(),
      ],
    },
  ],
  seed: {
    site_settings: [
      {
        id: "5a4216d9-6fb1-4a1a-93fd-62b5ec90fa30",
        company_name: "DEERE-SHOP",
        phone: "",
        email: "",
        primary_color: "#4C8F2B",
        accent_color: "#FFC107",
        primary_cta_text: "Получить консультацию",
        primary_cta_url: "/contacts#consultation",
        footer_text:
          "Каталог комплектующих John Deere и подбор решений под задачи клиента.",
      },
    ],
  },
};
